# Generated by Django 4.2.6 on 2023-10-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_plate_no",
                    models.CharField(
                        max_length=16, verbose_name="License plate number"
                    ),
                ),
                (
                    "vin_code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="VIN code"
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        max_length=64, verbose_name="Client's name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
            },
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=64, verbose_name="Make")),
                (
                    "model",
                    models.CharField(max_length=64, verbose_name="Model"),
                ),
                ("year", models.IntegerField(verbose_name="Year")),
                (
                    "engine_type",
                    models.CharField(
                        max_length=64, verbose_name="Engine type"
                    ),
                ),
            ],
            options={
                "verbose_name": "Car model",
                "verbose_name_plural": "Car models",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(auto_now_add=True, verbose_name="Date"),
                ),
                ("total_price", models.FloatField(verbose_name="Total price")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="service.car",
                        verbose_name="Car",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Name"),
                ),
                ("price", models.FloatField(verbose_name="Price")),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="service.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="service.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order line",
                "verbose_name_plural": "Order lines",
            },
        ),
        migrations.AddField(
            model_name="car",
            name="car_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="service.carmodel",
                verbose_name="Model",
            ),
        ),
    ]
