# Generated by Django 4.2.6 on 2023-10-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-id"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("N", "New"),
                    ("D", "Declined"),
                    ("A", "Accepted"),
                    ("P", "In Progress"),
                    ("C", "Completed"),
                ],
                default="N",
                max_length=1,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="license_plate_no",
            field=models.CharField(
                help_text="Enter car's licence plate number (it need not be unique, since cars can be from different countries)",
                max_length=16,
                verbose_name="License plate number",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="vin_code",
            field=models.CharField(
                help_text="Enter car's vin code (it must be unique)",
                max_length=32,
                unique=True,
                verbose_name="VIN code",
            ),
        ),
    ]
