# Generated by Django 4.2.6 on 2023-10-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_alter_order_options_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="description",
            field=models.TextField(
                default="", max_length=2048, verbose_name="Description"
            ),
        ),
    ]
