# Generated by Django 4.2.6 on 2023-10-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0003_car_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.TextField(
                default="", max_length=2048, verbose_name="Description"
            ),
        ),
    ]
