# Generated by Django 4.2.6 on 2023-10-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0004_service_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmodel",
            name="description",
            field=models.TextField(
                default="", max_length=2048, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="carmodel",
            name="fuel_type",
            field=models.CharField(
                default="Diesel", max_length=64, verbose_name="Fuel type"
            ),
            preserve_default=False,
        ),
    ]
