# Generated by Django 4.2.6 on 2023-10-22 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0006_remove_order_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderline",
            name="price",
        ),
    ]
