# Generated by Django 4.2.6 on 2023-10-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0008_remove_car_description_car_observations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="quantity",
            field=models.IntegerField(default=1, verbose_name="Quantity"),
        ),
    ]
