# Generated by Django 4.2.6 on 2023-10-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0009_alter_orderline_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="car_photos",
                verbose_name="Photo",
            ),
        ),
    ]
