# Generated by Django 4.2.6 on 2023-10-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0011_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="deadline",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deadline"
            ),
        ),
    ]
