# Generated by Django 4.2.6 on 2023-10-28 16:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0012_order_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmodel",
            name="description",
            field=tinymce.models.HTMLField(
                default="", max_length=4096, verbose_name="Description"
            ),
        ),
    ]
