# Generated by Django 4.2.7 on 2023-11-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0016_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="vin_code",
            field=models.CharField(
                help_text="Enter car's VIN code (it must be unique)",
                max_length=17,
                unique=True,
                verbose_name="VIN code",
            ),
        ),
    ]
