# Generated by Django 4.2.7 on 2023-11-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0017_alter_car_vin_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="photo",
            field=models.ImageField(
                default="car_photos/no_photo.jpg",
                upload_to="car_photos",
                verbose_name="Photo",
            ),
        ),
    ]
