# Generated by Django 4.2.7 on 2023-11-06 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0018_alter_car_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={
                "ordering": ["id"],
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["id"],
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
    ]
